// const users100 = [
//   {
//     firstName: "Fredrick",
//     lastName: "Redd",
//     username: "fredrickredd@gmail.com",
//     password: "126554407",
//   },
//   {
//     firstName: "Earl",
//     lastName: "Cheney",
//     username: "earlcheney@gmail.com",
//     password: "113273767",
//   },
//   {
//     firstName: "Kari",
//     lastName: "Langley",
//     username: "karilangley@gmail.com",
//     password: "117424209",
//   },
//   {
//     firstName: "Brayan",
//     lastName: "Arrington",
//     username: "brayanarrington@gmail.com",
//     password: "113972037",
//   },
//   {
//     firstName: "Joseph",
//     lastName: "Ogden",
//     username: "josephogden@gmail.com",
//     password: "140785583",
//   },
//   {
//     firstName: "Bradly",
//     lastName: "Bland",
//     username: "bradlybland@gmail.com",
//     password: "106446467",
//   },
//   {
//     firstName: "Jarred",
//     lastName: "Malik",
//     username: "jarredmalik@gmail.com",
//     password: "129008972",
//   },
//   {
//     firstName: "Marcelo",
//     lastName: "Weir",
//     username: "marceloweir@gmail.com",
//     password: "103685545",
//   },
//   {
//     firstName: "Candice",
//     lastName: "Colson",
//     username: "candicecolson@gmail.com",
//     password: "138457118",
//   },
//   {
//     firstName: "Ryleigh",
//     lastName: "Bourne",
//     username: "ryleighbourne@gmail.com",
//     password: "99385780",
//   },
//   {
//     firstName: "Keven",
//     lastName: "Hays",
//     username: "kevenhays@gmail.com",
//     password: "141559880",
//   },
//   {
//     firstName: "Rohan",
//     lastName: "Cote",
//     username: "rohancote@gmail.com",
//     password: "134859939",
//   },
//   {
//     firstName: "Juliette",
//     lastName: "Quigley",
//     username: "juliettequigley@gmail.com",
//     password: "111686140",
//   },
//   {
//     firstName: "Edgar",
//     lastName: "Royer",
//     username: "edgarroyer@gmail.com",
//     password: "133294584",
//   },
//   {
//     firstName: "Roland",
//     lastName: "Hartley",
//     username: "rolandhartley@gmail.com",
//     password: "102586480",
//   },
//   {
//     firstName: "Dixie",
//     lastName: "Santana",
//     username: "dixiesantana@gmail.com",
//     password: "116841073",
//   },
//   {
//     firstName: "Selah",
//     lastName: "Nicholson",
//     username: "selahnicholson@gmail.com",
//     password: "137091594",
//   },
//   {
//     firstName: "India",
//     lastName: "Rosado",
//     username: "indiarosado@gmail.com",
//     password: "130127382",
//   },
//   {
//     firstName: "Calli",
//     lastName: "Harlow",
//     username: "calliharlow@gmail.com",
//     password: "122160481",
//   },
//   {
//     firstName: "Cortez",
//     lastName: "Pantoja",
//     username: "cortezpantoja@gmail.com",
//     password: "139707441",
//   },
//   {
//     firstName: "Abigale",
//     lastName: "Straub",
//     username: "abigalestraub@gmail.com",
//     password: "100926397",
//   },
//   {
//     firstName: "Omar",
//     lastName: "Landis",
//     username: "omarlandis@gmail.com",
//     password: "108012061",
//   },
//   {
//     firstName: "Desiree",
//     lastName: "Overton",
//     username: "desireeoverton@gmail.com",
//     password: "129085813",
//   },
//   {
//     firstName: "Latrell",
//     lastName: "Loveless",
//     username: "latrellloveless@gmail.com",
//     password: "140996637",
//   },
//   {
//     firstName: "Pierre",
//     lastName: "Edmondson",
//     username: "pierreedmondson@gmail.com",
//     password: "113110217",
//   },
//   {
//     firstName: "Jensen",
//     lastName: "Renner",
//     username: "jensenrenner@gmail.com",
//     password: "118234638",
//   },
//   {
//     firstName: "Jordyn",
//     lastName: "Roldan",
//     username: "jordynroldan@gmail.com",
//     password: "139378483",
//   },
//   {
//     firstName: "Hassan",
//     lastName: "Hager",
//     username: "hassanhager@gmail.com",
//     password: "112216876",
//   },
//   {
//     firstName: "Bailee",
//     lastName: "Mays",
//     username: "baileemays@gmail.com",
//     password: "139941271",
//   },
//   {
//     firstName: "Liam",
//     lastName: "Kaminski",
//     username: "liamkaminski@gmail.com",
//     password: "118518633",
//   },
//   {
//     firstName: "Jakobe",
//     lastName: "Camacho",
//     username: "jakobecamacho@gmail.com",
//     password: "111277640",
//   },
//   {
//     firstName: "Bridger",
//     lastName: "Bonilla",
//     username: "bridgerbonilla@gmail.com",
//     password: "99570687",
//   },
//   {
//     firstName: "Ashanti",
//     lastName: "Buchanan",
//     username: "ashantibuchanan@gmail.com",
//     password: "113090510",
//   },
//   {
//     firstName: "Ayleen",
//     lastName: "Tubbs",
//     username: "ayleentubbs@gmail.com",
//     password: "101758062",
//   },
//   {
//     firstName: "Daron",
//     lastName: "Burdick",
//     username: "daronburdick@gmail.com",
//     password: "103967424",
//   },
//   {
//     firstName: "Tre",
//     lastName: "McGraw",
//     username: "tremcgraw@gmail.com",
//     password: "125180940",
//   },
//   {
//     firstName: "Charles",
//     lastName: "Simms",
//     username: "charlessimms@gmail.com",
//     password: "137540963",
//   },
//   {
//     firstName: "Callie",
//     lastName: "Barker",
//     username: "calliebarker@gmail.com",
//     password: "103459884",
//   },
//   {
//     firstName: "Averi",
//     lastName: "Strand",
//     username: "averistrand@gmail.com",
//     password: "106686712",
//   },
//   {
//     firstName: "Adriana",
//     lastName: "Hutton",
//     username: "adrianahutton@gmail.com",
//     password: "132513946",
//   },
//   {
//     firstName: "Siera",
//     lastName: "Lennon",
//     username: "sieralennon@gmail.com",
//     password: "102618672",
//   },
//   {
//     firstName: "Kelsea",
//     lastName: "Findley",
//     username: "kelseafindley@gmail.com",
//     password: "129201358",
//   },
//   {
//     firstName: "Kearra",
//     lastName: "Pond",
//     username: "kearrapond@gmail.com",
//     password: "102156414",
//   },
//   {
//     firstName: "Tiffani",
//     lastName: "Hassan",
//     username: "tiffanihassan@gmail.com",
//     password: "133670060",
//   },
//   {
//     firstName: "Asia",
//     lastName: "Colwell",
//     username: "asiacolwell@gmail.com",
//     password: "138631361",
//   },
//   {
//     firstName: "Jewel",
//     lastName: "Grove",
//     username: "jewelgrove@gmail.com",
//     password: "113880707",
//   },
//   {
//     firstName: "Jazmine",
//     lastName: "McCarty",
//     username: "jazminemccarty@gmail.com",
//     password: "136818771",
//   },
//   {
//     firstName: "Carlo",
//     lastName: "Parra",
//     username: "carloparra@gmail.com",
//     password: "138476645",
//   },
//   {
//     firstName: "Gretchen",
//     lastName: "Grubb",
//     username: "gretchengrubb@gmail.com",
//     password: "127133323",
//   },
//   {
//     firstName: "Dylan",
//     lastName: "Talbot",
//     username: "dylantalbot@gmail.com",
//     password: "115877623",
//   },
//   {
//     firstName: "Tyrique",
//     lastName: "Song",
//     username: "tyriquesong@gmail.com",
//     password: "113041489",
//   },
//   {
//     firstName: "Kristofer",
//     lastName: "Guest",
//     username: "kristoferguest@gmail.com",
//     password: "125135744",
//   },
//   {
//     firstName: "Ivana",
//     lastName: "Andrade",
//     username: "ivanaandrade@gmail.com",
//     password: "103968365",
//   },
//   {
//     firstName: "Tavon",
//     lastName: "Serrano",
//     username: "tavonserrano@gmail.com",
//     password: "129797407",
//   },
//   {
//     firstName: "Perla",
//     lastName: "Leary",
//     username: "perlaleary@gmail.com",
//     password: "129628973",
//   },
//   {
//     firstName: "Aditya",
//     lastName: "Katz",
//     username: "adityakatz@gmail.com",
//     password: "120341642",
//   },
//   {
//     firstName: "Oswaldo",
//     lastName: "Bratcher",
//     username: "oswaldobratcher@gmail.com",
//     password: "105873334",
//   },
//   {
//     firstName: "Denver",
//     lastName: "Pickett",
//     username: "denverpickett@gmail.com",
//     password: "130211907",
//   },
//   {
//     firstName: "Roger",
//     lastName: "Brice",
//     username: "rogerbrice@gmail.com",
//     password: "118254050",
//   },
//   {
//     firstName: "Tanner",
//     lastName: "Boston",
//     username: "tannerboston@gmail.com",
//     password: "129725020",
//   },
//   {
//     firstName: "Reginald",
//     lastName: "Hoover",
//     username: "reginaldhoover@gmail.com",
//     password: "125243545",
//   },
//   {
//     firstName: "Landen",
//     lastName: "Liang",
//     username: "landenliang@gmail.com",
//     password: "122806647",
//   },
//   {
//     firstName: "Susanna",
//     lastName: "Shepard",
//     username: "susannashepard@gmail.com",
//     password: "134689734",
//   },
//   {
//     firstName: "Remington",
//     lastName: "Tyree",
//     username: "remingtontyree@gmail.com",
//     password: "136613382",
//   },
//   {
//     firstName: "Lexi",
//     lastName: "Dempsey",
//     username: "lexidempsey@gmail.com",
//     password: "117766059",
//   },
//   {
//     firstName: "Danica",
//     lastName: "Reeder",
//     username: "danicareeder@gmail.com",
//     password: "112063240",
//   },
//   {
//     firstName: "Ashton",
//     lastName: "Colby",
//     username: "ashtoncolby@gmail.com",
//     password: "135406917",
//   },
//   {
//     firstName: "Jacquelin",
//     lastName: "Bray",
//     username: "jacquelinbray@gmail.com",
//     password: "133298396",
//   },
//   {
//     firstName: "Kierstin",
//     lastName: "Daniels",
//     username: "kierstindaniels@gmail.com",
//     password: "105000028",
//   },
//   {
//     firstName: "Eddie",
//     lastName: "Breeden",
//     username: "eddiebreeden@gmail.com",
//     password: "125126122",
//   },
//   {
//     firstName: "Owen",
//     lastName: "Metz",
//     username: "owenmetz@gmail.com",
//     password: "109316212",
//   },
//   {
//     firstName: "Leeann",
//     lastName: "Lord",
//     username: "leeannlord@gmail.com",
//     password: "112417378",
//   },
//   {
//     firstName: "Abbie",
//     lastName: "Dill",
//     username: "abbiedill@gmail.com",
//     password: "123952174",
//   },
//   {
//     firstName: "Billie",
//     lastName: "Marr",
//     username: "billiemarr@gmail.com",
//     password: "102581683",
//   },
//   {
//     firstName: "Bryanna",
//     lastName: "Hiatt",
//     username: "bryannahiatt@gmail.com",
//     password: "106121583",
//   },
//   {
//     firstName: "Collin",
//     lastName: "Robles",
//     username: "collinrobles@gmail.com",
//     password: "140483857",
//   },
//   {
//     firstName: "Rita",
//     lastName: "Holland",
//     username: "ritaholland@gmail.com",
//     password: "101710212",
//   },
//   {
//     firstName: "Kailyn",
//     lastName: "Kovach",
//     username: "kailynkovach@gmail.com",
//     password: "98807616",
//   },
//   {
//     firstName: "Gideon",
//     lastName: "Staples",
//     username: "gideonstaples@gmail.com",
//     password: "139969853",
//   },
//   {
//     firstName: "Braydon",
//     lastName: "Higdon",
//     username: "braydonhigdon@gmail.com",
//     password: "125300478",
//   },
//   {
//     firstName: "Anya",
//     lastName: "Keefe",
//     username: "anyakeefe@gmail.com",
//     password: "109964817",
//   },
//   {
//     firstName: "Lena",
//     lastName: "Rucker",
//     username: "lenarucker@gmail.com",
//     password: "127648136",
//   },
//   {
//     firstName: "Carlos",
//     lastName: "Garnett",
//     username: "carlosgarnett@gmail.com",
//     password: "129402628",
//   },
//   {
//     firstName: "Carter",
//     lastName: "Baron",
//     username: "carterbaron@gmail.com",
//     password: "114766317",
//   },
//   {
//     firstName: "Aysha",
//     lastName: "Christie",
//     username: "ayshachristie@gmail.com",
//     password: "99080551",
//   },
//   {
//     firstName: "Gunnar",
//     lastName: "Marion",
//     username: "gunnarmarion@gmail.com",
//     password: "127730080",
//   },
//   {
//     firstName: "Xzavier",
//     lastName: "Li",
//     username: "xzavierli@gmail.com",
//     password: "124231879",
//   },
//   {
//     firstName: "Jacob",
//     lastName: "Dewitt",
//     username: "jacobdewitt@gmail.com",
//     password: "129159186",
//   },
//   {
//     firstName: "Herman",
//     lastName: "Street",
//     username: "hermanstreet@gmail.com",
//     password: "128147242",
//   },
//   {
//     firstName: "Antoine",
//     lastName: "Corral",
//     username: "antoinecorral@gmail.com",
//     password: "115579102",
//   },
//   {
//     firstName: "Angelica",
//     lastName: "Lim",
//     username: "angelicalim@gmail.com",
//     password: "101239242",
//   },
//   {
//     firstName: "Shaelyn",
//     lastName: "Tisdale",
//     username: "shaelyntisdale@gmail.com",
//     password: "104608509",
//   },
//   {
//     firstName: "Thaddeus",
//     lastName: "Rourke",
//     username: "thaddeusrourke@gmail.com",
//     password: "119277485",
//   },
//   {
//     firstName: "Chad",
//     lastName: "Duggan",
//     username: "chadduggan@gmail.com",
//     password: "135075944",
//   },
//   {
//     firstName: "Morgan",
//     lastName: "Padgett",
//     username: "morganpadgett@gmail.com",
//     password: "131617917",
//   },
//   {
//     firstName: "Yehuda",
//     lastName: "Abreu",
//     username: "yehudaabreu@gmail.com",
//     password: "129743232",
//   },
//   {
//     firstName: "Nehemiah",
//     lastName: "Conley",
//     username: "nehemiahconley@gmail.com",
//     password: "121713495",
//   },
//   {
//     firstName: "Colton",
//     lastName: "Cortez",
//     username: "coltoncortez@gmail.com",
//     password: "125168987",
//   },
//   {
//     firstName: "Cara",
//     lastName: "McDaniel",
//     username: "caramcdaniel@gmail.com",
//     password: "108174296",
//   },
//   {
//     firstName: "Coby",
//     lastName: "Valenzuela",
//     username: "cobyvalenzuela@gmail.com",
//     password: "122524930",
//   },
// ];

// import axios from "axios";

// users100.forEach((user) => {
//   async function request() {
//     await axios.post(
//       "https://congenial-spork-45vxjvq4v44hqjx6-3000.app.github.dev/api/v1/user/signup",
//       {
//         firstName: user.firstName,
//         lastName: user.lastName,
//         username: user.username,
//         password: user.password,
//       }
//     );
//   }
//   request();
// });
